name: FirstWorkFlow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print Message
        run: echo "Hello Chetan"
      - name: print bye
        run: echo "bye Chetan"
  
